apiVersion: apps/v1
kind: Deployment
metadata:
  name: javap1
  labels:
    app: java-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-project
  template:
    metadata:
      labels:
        app: java-project
    spec:
      containers:
      - name: my-container
        image: 339712975277.dkr.ecr.us-east-1.amazonaws.com/gabogrobier:latest
        ports:
        - containerPort: 8080
