name: test-java
on: 
    push:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: obtener y chechear el repositorio
              uses: actions/checkout@v4
            
            - name: configurar java
              uses: actions/setup-java@v2
              with: 
                    java-version: '17'
                    distribution: 'temurin'
            
            - name: test java
              run: mvn test